### PR TITLE
Add support for self-referential structures.

### PR DESCRIPTION
**Pull request by kylelemons**
See issue #16 and pulls #1 and #17 for context.

### CODE REVIEW

**Comment by navytux** [comment]
follow-up: https://github.com/kylelemons/godebug/pull/17#issuecomment-323615023, #19.

**Comment by navytux** [comment]
review feedback: https://github.com/kylelemons/godebug/pull/17#issuecomment-323983759.

**Comment by crunk1** [comment]
@adjackura

**Comment by crunk1** [comment]
According to your examples:

```
	// Output:
 	// <#1> {
 	//  Value: 1,
 	//  Next: {
 	//   Value: 2,
 	//   Next: {
 	//    Value: 3,
 	//    Next: <see #1>,
 	//   },
 	//  },
 	// }
```

Are the "<#1>" tags done for EVERY pointer, or only truncated pointers?

Also, are you not a fan of providing the data type information? e.g. <SomeType at 0x...> for pointers and <SomeType> for nonpointers?

It would look something like

```
	// Output:
 	// <ListNode at 0x123> {
 	//  Value: <int>1,
 	//  Next: <ListNode at 0x456> {
 	//   Value: <int>2,
 	//   Next: <ListNode at 0x789> {
 	//    Value: <int>3,
 	//    Next: <ListNode at 0x123 truncated>,  // well, "truncated", "recursive", or etc.
 	//   },
 	//  },
 	// }
```

I guess that would making string-based diffing a little harder. You'd have to diff before adding the memory address information.

**Comment by kylelemons** [comment]
Those references are added only for pointers that are actually referenced
from their pointee (aka circular references), and type/address information
is deliberately omitted because I actually don't want to preclude you from
diffing separate types that are structurally the same.  (This is not
DeepEqual, which is much more strict)

**Comment by crunk1** [comment]
Makes sense to me. I think your solution seems fine. I'd probably say "pointer to #x" instead of "see #x", but that's just a matter of preference.

**Comment by crunk1** [comment]
Any update on this?

**Comment by kylelemons** [comment]
Sorry for the delay, work has been a bit crazy lately and I'm about to fly to the other side of the world again for a month.  I've finally had time to do the `writeTo` refactor that I was wanting to do, and I wrapped the self-referential changes into that because I forgot to split them out when committing :).

Before I pull this I need to run it against some of the projects that I know make heavy use of pretty to make sure I'm not going to break anyone, which won't be able to happen until I get back unfortunately.

**Comment by crunk1** [comment]
Sounds good to me! Thanks!

**Comment by kylelemons** [comment]
I have merged my selfref branch into mainline and tagged a v1.1.0 release. Thanks for all of the suggestions!

**Pull request closed without merging**
