### PR TITLE
Remove padding from Diffable output

### PR DESCRIPTION
**Pull request by mgood**
Thanks, this has been really useful for our testing, but I noticed an issue when diffing some maps.

When comparing maps where the padding differs between the two sets of keys, the
diff will include keys that were unchanged except for the padding difference.

For example, Arthur Dent appears as a diff due to different padding:
```
{
  Crew: {
-        Arthur Dent:       "Along for the Ride",
-        Zaphod Beeblebrox: "Galactic President",
+        Arthur Dent: "Along for the Ride",
        },
 }
```

This omits padding when `Diffable = true` so that the diff output is consistent
to prevent these spurious diffs.

So, after this change it would produce:
```
{
 Crew: {
  Arthur Dent: "Along for the Ride",
- Zaphod Beeblebrox: "Galactic President",
 },
}
```

I also included a newline even for empty maps, so that the diff output there would be more compact as well.

Before comparing an empty map would produce a diff like:
```
-{}
+{
+ foo: "bar",
+}
```

and after:
```
 {
+ foo: "bar",
 }
```

### CODE REVIEW

**Comment by kylelemons** [comment]
Hey Matt!  Those improvements look great; unfortunately, since Google owns the copyright on this code, I'm required to have contributors sign the [Google Contributor License Agreement](cla.developers.google.com) before I can accept pull requests :(.

**Comment by mgood** [comment]
No problem, I've just signed it.

**Comment by mgood** [comment]
:+1: Thanks!

**Comment by kylelemons** [comment]
No problem at all.  You motivated me to make some of the other fixes I've been wanting to get in for awhile too, so thanks :).

**Pull request merged**
